---
# Crypto Policy tasks file for ansible-role-nnt-agent

- name: "Collect existing System-Wide Cryptographic Policies"
  ansible.builtin.shell:
    cmd: update-crypto-policies --show
  register: crypto

- name: "Set fact for System-Wide Cryptographic Policy"
  ansible.builtin.set_fact:
    crypto: "{{ crypto.stdout }}"

- name: "Add custom NNT GEN7AGENT System-Wide Cryptographic Policy (if missing)"
  ansible.builtin.copy:
    dest: /usr/share/crypto-policies/policies/modules/GEN7AGENT.pmod
    owner: root
    group: root
    mode: '0644'
    content: |
      # This subpolicy adds SHA1 hash and signature support
      hash = SHA1+
      sign = RSA-SHA1+
  when:
    - crypto is not search('GEN7AGENT')

- name: "Apply new System-Wide Cryptographic Policies"
  ansible.builtin.shell:
    cmd: update-crypto-policies --set {{ crypto }}:GEN7AGENT
  when:
    - crypto is not search('GEN7AGENT')

- name: "Reboot host after new System-Wide Cryptographic Policies have been applied"
  ansible.builtin.reboot:
  when:
    - crypto is not search('GEN7AGENT')