---
# tasks file for ansible-role-nnt-agent

- name: "Include OS-specific variables"
  ansible.builtin.include_vars:
    file: "{{ ansible_os_family }}.yaml"

- name: "Test Access to Proxy Server"
  ansible.builtin.uri:
    url: "{{ proxy_protocol }}://{{ proxy_host }}:{{ proxy_port }}"
    method: GET
    validate_certs: no
    status_code: [200, 400]
  when: proxy | bool

- name: "Check for Hub Server Name Resolution"
  ansible.builtin.shell:
    cmd: nslookup "{{ hub_host }}"
  ignore_errors: true
  register: resolve

- name: "Set resolve fact"
  ansible.builtin.set_fact:
    resolve: true
  when:
    - resolve.rc == 0

- name: "Add Hub Server IP and Hostname to the /etc/hosts for Name Resolution"
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ hub_ip }}\t{{ hub_host }}"
    insertafter: EOF
    state: present
  when: not resolve | bool

- name: "Test Access to Hub Server (Proxy)"
  ansible.builtin.uri:
    url: "{{ hub_url }}"
    method: GET
    validate_certs: no
    status_code: [404]
  environment:
    http_proxy: "{{ proxy_protocol }}://{{ proxy_host }}:{{ proxy_port }}"
    https_proxy: "{{ proxy_protocol }}://{{ proxy_host }}:{{ proxy_port }}"
  when: proxy | bool

- name: "Test Access to Hub Server"
  ansible.builtin.uri:
    url: "{{ hub_url }}"
    method: GET
    validate_certs: no
    status_code: [404]
  when: not proxy | bool

- name: "Include tasks from assert playbook"
  ansible.builtin.include_tasks: assert.yaml

- name: "Include tasks from lookup playbook"
  ansible.builtin.include_tasks: lookup.yaml

- name: "Include tasks from crypto playbook"
  ansible.builtin.include_tasks: crypto.yaml
  when:
    - ansible_facts['os_family'] == 'RedHat'
    - ansible_distribution_major_version >= "8"

- name: "Include tasks from install playbook"
  ansible.builtin.include_tasks: install.yaml
  when:
    - install is defined
    - install | bool

- name: "Include tasks from upgrade playbook"
  ansible.builtin.include_tasks: upgrade.yaml
  when:
    - upgrade is defined
    - upgrade | bool